default_language_version:
  python: python3

exclude: |
  (?x)^(
    tools/.*py|
    build/cache.py|
    build/common_compiler_flags.py
  )

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: \.py$
        types_or: [text]

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.4
    hooks:
      - id: typos